# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: NYC Day Care
description: 
author:
  name: 
  email: marc@marcshifflett.com

# Grunt handles images and assets.
exclude: ['Procfile', 'README.md', 'CNAME',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# exclude: ['img', 'css', 'js', 'fonts', "Gruntfile.js", "package.json", "node_modules"]

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet

#   extensions: ['fenced_code_blocks', 'smart']

pygments: true

#baseurl: /jekyllrb

title_tag_text: Daycare Map NYC
h1_tag_text: Daycare Map NYC